### ISSUE TITLE
make error when building qgis_gui

### ISSUE THREAD

**Issue by nextstopsun** [qgis/homebrew-qgisdev#15]
make Error 2 at 55%. Brew gist logs are [here](https://gist.github.com/anonymous/8bbcb2842e8cae8fae46807262f4bf29). Any suggestions?

**Comment by dakcarto** [comment]
Hi @nextstopsun, thanks for reporting.

I don't actually see any build errors in your `make` output, just the final `make Error 2` (return from `make`, indicating an error did occur). Did you maybe run out of OS resources during the build, e.g. disk space, RAM, etc.?

You maybe can try any of the following:

* `brew install qgis3-dev` with no options
* Add a `ENV.deparallelize` line to the formula, right before the [call to `make`](https://github.com/qgis/homebrew-qgisdev/blob/master/Formula/qgis3-dev.rb#L259). This will cause a very slow build, but keep things in order, so you can maybe align the build error at the end.
* Edit formula and [add `Ninja` as the CMake generator](https://blog.kitware.com/cmake-building-with-all-your-cores/) to `cmake` options, [after this line](https://github.com/qgis/homebrew-qgisdev/blob/master/Formula/qgis3-dev.rb#L152). This will allow for multi-core builds, but keep error output in-line (or _should_).

**Comment by dakcarto** [comment]
Any update here?

**Comment by nextstopsun** [comment]
Sorry, been quite busy recently, I'll try the build next week and get back to this thread. Please don't close it yet.

**Comment by dakcarto** [comment]
Please retry. No issues here on 10.11.6 with latest `qgis3-dev`, which fully builds against Qt 5.8.0. See known issues in #22.

**Comment by oeon** [comment]
I'm getting a similar error. Although I recently (May 5th) had a successful build following the [terminal.app build](https://github.com/qgis/homebrew-qgisdev/blob/master/development/README.md#configurebuildinstall-qgis-in-a-terminalapp-session).

A gist-log can be found [here](https://gist.github.com/oeon/cd5aee1e0417fd4f4dbc7137ad0166df), please advise anything I might be able to do to help test.

**Comment by dakcarto** [comment]
Any updates here? Not having issues on 10.11, 10.12 or 10.13 here.

**Comment by oeon** [comment]
@dakcarto I've been able to build handfuls of recent versions on 10.12 (including the most recent)...no longer an issue for me.
