### ISSUE TITLE
Qt5UiPlugin error

### ISSUE THREAD

**Issue by stamogis** [qgis/homebrew-qgisdev#17]
Sorry I am a complete newbie and not familiar with homebrew. I've done a fresh qgisdev installation. An error message appears during installation of the qgis3-dev package:

The installation package was faulty and contained
     "/usr/local/opt/qt5/lib/cmake/Qt5UiPlugin/Qt5UiPluginConfig.cmake"
  but not all the files it references.
Call Stack (most recent call first):
  /usr/local/opt/qt5/lib/cmake/Qt5UiPlugin/Qt5UiPluginConfig.cmake:33 (_qt5_UiPlugin_check_file_exists)
  src/customwidgets/CMakeLists.txt:5 (FIND_PACKAGE)

What is wrong and how can I fix the error?

Regards Burghardt

**Comment by dakcarto** [comment]
Hi @stamogis, thanks for reporting.

This is an upstream bug: https://bugreports.qt.io/browse/QTBUG-57656

However, it is not the only Homebrew formula that fails to comiple against Qt 5.8.0. So, I refactored the `qgis3-dev` build to explicitly use Qt 5.7.

Please try again. Thanks.

**Comment by stamogis** [comment]
Hi,
I've just successfully compiled qgis3-dev. Wonderful, many thanks!
Regards Burghardt
