### ISSUE TITLE
Configuring fails: Could NOT find PythonInterp

### ISSUE THREAD

**Issue by nextstopsun** [qgis/homebrew-qgisdev#2]
I'm trying to build on OS X 10.11 and I get a configure error.

```CMake Error at /usr/local/Cellar/cmake/3.7.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "3" (found /usr/local/bin/python3)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.7.1/share/cmake/Modules/FindPythonInterp.cmake:151 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:649 (FIND_PACKAGE)
```

Python 3.5.2 is installed via Homebrew, I can run it with `python3`.

**Comment by dakcarto** [comment]
Hi @nextstopsun, thanks for reporting.

I ran into this during testing, and for me, it was because I had `PYTHON...` environ variables still pointing to Python 2 locations. If you have any `PYTHON...` environ variables, please unset them and rely upon only the `python3` found on PATH, then try again.

**Comment by nextstopsun** [comment]
@dakcarto Larry, thanks for clarifying! 

I've unset PYTHONPATH prior to installing python3. Checked `env` - it doesn't show anything python related. 
What exact env vars should I set explicitly to make it work?

**Comment by dakcarto** [comment]
HI @nextstopsun, please try this:

Download this gist (`test-cmake-find-pyinterp.cmake`):
https://gist.github.com/dakcarto/1f14287dd4d18ffc6db6ceae6ad0cab1

Then, in the same Terminal shell that you are using for `brew install qgis3-dev` run the following, substituting `<path-to>`:
```
cmake -DQGIS_SRC="$(brew --cache)/qgis3-dev--git" -P <path-to>/test-cmake-find-pyinterp.cmake
```

Then, post the CMake output from Terminal _and_ the dump file listed after "Dumping current CMake variables to ..." at end of output (consider **sanitizing the dump file** prior to posting, if you are concerned with sensitive paths).

Thanks!

**Comment by nextstopsun** [comment]
@dakcarto Larry, thanks for your help!
`test-cmake-find-pyinterp.cmake` output is:
```
cmake -DQGIS_SRC="$(brew --cache)/qgis3-dev--git" -P /Users/nextstopsun/Work/qgis-homebrew/test-cmake-find-pyinterp.cmake
-- CMake's PythonInterp module
-- Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.5.2", minimum required is "3") 
-- QGIS's FindPythonLibrary module
-- Found Python executable: /usr/local/bin/python3
-- Found Python version: 3.5.2
-- Found Python library: /usr/local/Frameworks/Python.framework/Versions/3.5/Python
-- Found Python site-pacakges: /usr/local/lib/python3.5/site-packages
-- CMake's PythonLibs module
-- Found PythonLibs: /usr/local/Frameworks/Python.framework/Versions/3.5/Python (found suitable version "3.5.2", minimum required is "3") 
-- Dumping current CMake variables to ...
  /Users/nextstopsun/Library/Caches/Homebrew/qgis3-dev--git/test-cmake-find-pyinterp_cmake-vars.txt
```


The `test-cmake-find-pyinterp_cmake-vars.txt` is in this [gist](https://gist.github.com/nextstopsun/cd8128d84ef1c84723c83d0fcf995d85)

I can't find anything suspicious related to python 2. 
Any clues?

**Comment by nextstopsun** [comment]
I've noticed, that though I do `unset PYTHONPATH` brew outputs this

```
HEAD is now at 08ee180 [FEATURE] cpt-city catalog support in color ramp's gradient-only mode (#3832)
Failed to import the site module
Your PYTHONPATH points to a site-packages dir for Python 2.x but you are running Python 3.x!
     PYTHONPATH is currently: "/usr/local/lib/python2.7/site-packages"
     You should `unset PYTHONPATH` to fix this.
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'
```

`echo $PYTHONPATH` returns an empty value.

**Comment by nextstopsun** [comment]
Setting explicitly  `export PYTHONPATH=/usr/local/lib/python3.5/site-packages` gets the build running, but I guess this isn't a universal solution.

**Comment by dakcarto** [comment]
@nextstopsun good to know. Thanks for the update on this. I think this is isolated to your setup, though I'm at a loss as to how `PYTHONPATH is currently: "/usr/local/lib/python2.7/site-packages"` is getting set (maybe in $HOME site-packages via  a .pth file?).

Closing this issue, since it does not seem to be happening on other tester's environs. Please reopen if needed.

**Comment by MrBean947724451** [comment]
delete CMakeLists.txt which will  cache make config .If the first time you use python 2.7 ,the file can remerber python path,and use it . so JUST DELETE CMAKELISTS.TXT!
