### ISSUE TITLE
Building python gui bindings fails

### ISSUE THREAD

**Issue by m-kuhn** [qgis/homebrew-qgisdev#3]
An extract from the local terminal. I'm not sure if the messages show the error which is responsible for failing.

```
cd /tmp/qgis3-dev-20161201-31440-ndvdr6/build && /usr/local/Cellar/cmake/3.7.1/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/qgis3-dev-20161201-31440-ndvdr6 /tmp/qgis3-dev-20161201-31440-ndvdr6/tests/src/gui /tmp/qgis3-dev-20161201-31440-ndvdr6/build /tmp/qgis3-dev-20161201-31440-ndvdr6/build/tests/src/gui /tmp/qgis3-dev-20161201-31440-ndvdr6/build/tests/src/gui/CMakeFiles/qgis_keyvaluewidgettest.dir/DependInfo.cmake --color=
Scanning dependencies of target qgis_keyvaluewidgettest
sip: /usr/local/share/sip/Qt5/QtWidgets/qabstractbutton.sip:24: The struct/class has already been defined
make[2]: *** [python/gui/sip_guipart0.cpp] Error 1
make[2]: *** Deleting file `python/gui/sip_guipart0.cpp'
make[1]: *** [python/CMakeFiles/python_module_qgis__gui.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Full gist-logs (which interestingly don't contain the sip messages which can be seen above):
https://gist.github.com/m-kuhn/084432a587e7048f48ec9d86036e887c

**Comment by brncsk** [comment]
`brew unlink pyqt` solved this for me.

**Comment by dakcarto** [comment]
@brncsk, thanks for the update! I did not verify your report, but added `pyqt` to the `NoQt4Requirement` of `qgis3-dev` just to be sure (9dfd2c0).

@m-kuhn do you have `pyqt` (in Homebrew's [boneyard now](https://github.com/Homebrew/homebrew-boneyard) - since 15 days ago) installed and linked? If so, `brew update` and test new formula, or follow @brncsk suggestion.

**Comment by m-kuhn** [comment]
Yes, that did it, it now warns for linked `pyqt` and unlinking before building fixes builds.
Thanks a lot @brncsk and @dakcarto
