### ISSUE TITLE
Problem when building qgis3-dev

### ISSUE THREAD

**Issue by Malauch** [qgis/homebrew-qgisdev#31]
I tried to install qgis3-dev using homebrew but I have problem. Something stops building qgis3-dev and there is error: ninja: build stopped: subcommand failed.

I'm totally beginner with terminal and homebrew, so I don't have any idea where is a problem.

I attache txt file with all text/command from terminal.
[building qgis3-dev.txt](https://github.com/qgis/homebrew-qgisdev/files/1109130/building.qgis3-dev.txt)

**Comment by dakcarto** [comment]
Hi @Malauch, thanks for reporting!

Please try with latest `qgis3-dev` formula updates. Thanks!

**Comment by dakcarto** [comment]
@Malauch any update? If not, please close issue. Thanks.

**Comment by beingalink** [comment]
I just tried the qgis3-dev formula and it also failed with a subcommand failure: <https://www.dropbox.com/s/iisl8ax6x7o2xqi/qgis3-dev_fail.txt?dl=0>

**Comment by dakcarto** [comment]
Hi @beingalink, thanks for reporting!

Please provide [Troubleshooting](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md) logs. The one you posted does not contain the actual error.

Also note that the compilation error _may be missing_ from any uploaded `brew gits-logs`. See: [Finding-a-parallel-job-compilation-error](https://github.com/OSGeo/homebrew-osgeo4mac/wiki/Finding-a-parallel-job-compilation-error)

**Comment by beingalink** [comment]
OK, I tried a 2nd time and now it magically worked and I got a qgis binary. Only issue I got so far is on startup:
```
Ein Fehler trat bei der Ausführung von Python-Code auf: 

TypeError: expected str, bytes or os.PathLike object, not NoneType 
Traceback (most recent call last):
  File "/usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/algs/grass7/Grass7AlgorithmProvider.py", line 73, in load
    Grass7Utils.grassHelpPath()))
  File "/usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/algs/grass7/Grass7Utils.py", line 506, in grassHelpPath
    localPath = os.path.join(Grass7Utils.path, 'docs/html')
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 78, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType


Python-Version: 3.6.3 (default, Oct 20 2017, 10:17:26) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)] 
QGIS-Version: 2.99.0-Master Master, af6b4cc 

Python-Pfad:
/usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing
/usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python
/Users/tolink/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/tolink/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python/plugins
/usr/local/opt/gdal2-python/lib/python3.6/site-packages
/usr/local/opt/qgis3-dev/lib/python3.6/site-packages
/usr/local/opt/qgis3-dev/libexec/python/lib/python/site-packages
/usr/local/lib/python3.6/site-packages
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/tolink/Library/Application Support/QGIS/QGIS3/profiles/default/python
```
When I close this popup the app opens just fine though.

**Comment by dakcarto** [comment]
@beingalink, I also get this error. It is an upstream source code error and unrelated to this `qgis3-dev` Homebrew formula. It needs reported and fixed.

**Comment by beingalink** [comment]
OK, thanks for the info and your help. From my side this issue could get closed.
