### ISSUE TITLE
libzip in qgis master

### ISSUE THREAD

**Issue by Gustry** [qgis/homebrew-qgisdev#33]
There is a new dependency in QGIS master about `libzip`, this is what I had to do:

```
brew install libzip
ln -vs /usr/local/opt/libzip/lib/libzip/include/zipconf.h /usr/local/include
```

CMAKE configuration
```
LIBZIP_INCLUDE_DIR= /usr/local/opt/libzip/lib/libzip/include
LIBZIP_LIBRARY= /usr/local/lib/libzip.dylib
```

**Comment by timlinux** [comment]
Thanks @Gustry this works for me...

**Comment by m-kuhn** [comment]
It works also without the `ln -vs`

**Comment by ismailsunni** [comment]
Just in case anyone know the solution of my issue.
I already did the comments from @Gustry , but unfortunatelly, I always got this error message:
```
/Users/ismailsunni/dev/cpp/QGIS/src/core/qgsziputils.cpp:21: error: 'zip.h' file not found
#include "zip.h"
         ^
```
I also have tried to do clean build, but I still got the issue.

**Comment by g-sherman** [comment]
I'm having the same issue. Solution above doesn't work for me, neither does building libzip from source.

**Comment by Gustry** [comment]
I'm not sure if @ismailsunni could fix it, but I saw he added
`${LIBZIP_INCLUDE_DIR}` in his `src/core/CMakeLists.txt` in the `INCLUDE_DIRECTORIES` on his pending PR.
Can you try @g-sherman?

**Comment by g-sherman** [comment]
LIBZIP_INCLUDE_DIR is already set in my cmake. zip.h exists in /usr/local/include. Adding 
make -I/usr/local/Cellar/libzip/1.2.0/include -I/usr/local/Cellar/libzip/1.2.0/lib/libzip/include
(obtained from pkg-config --cflags libzip) doesn't help.

**Comment by g-sherman** [comment]
Seems cmake isn't configuring the includes for libzip properly on OSX. If you use` make VERBOSE=1` you'll see they aren't there.  I captured the compile command for qgsziputils.cpp using `make VERBOSE=1`, added the includes obtained from `pkg-config --cflags libzip`, then compiled it separately without error.

**Comment by dakcarto** [comment]
Between https://github.com/qgis/QGIS/commit/83aa1ad and recent updates to `qgis3-dev` (specifically 133d229), it should be functioning now.

**Comment by dakcarto** [comment]
Closing, please reopen if needed.
