### ISSUE TITLE
failed install due to missing matplotlib

### ISSUE THREAD

**Issue by 3nids** [qgis/homebrew-qgisdev#38]
brew install qgis/qgisdev/qgis3-dev 
Updating Homebrew...
==> Installing qgis3-dev from qgis/qgisdev
Error: No available formula with the name "matplotlib" (dependency of qgis/qgisdev/qgis3-dev)

Any hint?

**Comment by 3nids** [comment]
had to install it manually 
`brew install homebrew/science/matplotlib`

**Comment by dakcarto** [comment]
Hi Denis, thanks for reporting!

Should be fixed in e7f4dea. Please test if you get a chance.

**Comment by 3nids** [comment]
already installed, but I guess it was the right thing to :)
thanks again!
