### ISSUE TITLE
Can't compile qgis3-dev

### ISSUE THREAD

**Issue by palmerj** [qgis/homebrew-qgisdev#41]
command run: `brew install qgis3-dev --with-3d --verbose`

Here's the error: https://gist.github.com/palmerj/dab76c99e32ae73213d580a7eb0ad90a

MacOSX Version 10.12.6

**Comment by dakcarto** [comment]
Hi @palmerj, thanks for reporting!

I've not updated my Homebrew for maybe a week and this is what I get:

```
$ pyrcc5 -version
pyrcc5 v5.9

$ pyrcc5 -h
PyQt5 resource compiler
Usage: pyrcc5 [options] <inputs>

Options:
    -o file           Write output to file rather than stdout
    -name name        Create an external initialization function with name
    -threshold level  Threshold to consider compressing files
    -compress level   Compress input files by level
    -root path        Prefix resource access path with root path
    -no-compress      Disable all compression
    -version          Display version
    -help             Display this information
```
which clearly shows `-name` support.

However, with [recent 5.9+ changelog entries](https://www.riverbankcomputing.com/static/Downloads/PyQt5/ChangeLog), that option has definitely been removed (guessing 5.9.1 is first version with that change):

```
2017-07-25  Phil Thompson  <phil@riverbankcomputing.com>

	* pyrcc/pyrcc_main.py, pyrcc/pyrccmod.sip, qpy/pyrcc/rcc.h:
	Removed the unimplemented -name option to pyrcc.
	[307cff7f1dbb] <5.9-maint>
```

So, this is something that needs updated in [PyQtMacros.cmake](https://github.com/qgis/QGIS/blob/master/cmake/PyQtMacros.cmake#L91) upstream, i.e. not related to the `qgis3-dev` formula code.

**Comment by dakcarto** [comment]
Yeah, sure enough:
```
$ pyrcc5 -version
pyrcc5 v5.9.1

$ pyrcc5 -h
PyQt5 resource compiler
Usage: pyrcc5 [options] <inputs>

Options:
    -o file           Write output to file rather than stdout
    -threshold level  Threshold to consider compressing files
    -compress level   Compress input files by level
    -root path        Prefix resource access path with root path
    -no-compress      Disable all compression
    -version          Display version
    -help             Display this information
```

Working on a fix.

**Comment by dakcarto** [comment]
Should be fixed in https://github.com/qgis/QGIS/commit/ff2a53c

Please try again.

**Comment by palmerj** [comment]
Thanks @dakcarto all working now!
