### ISSUE TITLE
Support for tabs in main window

### ISSUE THREAD

**Issue by Malauch** [qgis/homebrew-qgisdev#42]
I noticed that support for tabs is not consistent. After installation of qgis3-dev, table view was opening as a new tab in main window. However when I dragged table from tab to new window, then all new table views are opening as a new window (not tab in main window). In addition it's impossible to force qgis to open new table views as tabs, closing/opening app doesn't fix it.

It would be nice to have option to choose default option to open new table views as a tab or window and possibility to switch that mode for opened table.

**Comment by dakcarto** [comment]
Hi @Malauch, thanks for reporting!

Please file bugs not specific to this Homebrew formula, e.g. QGIS runtime bugs or features, at:
https://issues.qgis.org

**Comment by Malauch** [comment]
Sorry for trouble. I just noticed that tabs not so bad supported in QGIS3. It needs only activate bar with tabs (first option in View menu) then it works ok.
