### ISSUE TITLE
Processing plugin fails to load at startup

### ISSUE THREAD

**Issue by nextstopsun** [qgis/homebrew-qgisdev#6]
Don't know it's related to a brew formula or not, but I'm getting

```
Couldn't load plugin 'processing' 

FileNotFoundError: [Errno 2] 
No such file or directory: 
'/usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/algs/qgis/ui/PredefinedExpressionDialog.ui' 
```

at startup. 
I'll try to build on Arch machine to figure out if it's formula or upstream.

**Comment by m-kuhn** [comment]
That's an upstream issue https://travis-ci.org/qgis/QGIS/builds/181960567#L863
