### ISSUE TITLE
QGIS 3 is built without 3D support

### ISSUE THREAD

**Issue by alexgleith** [qgis/homebrew-qgisdev#65]
I don't know the specifics, but I think there's a flag when building QGIS where you can enable or disable the 3D viewer.

Is there any chance we can switch this on?

**Comment by Gustry** [comment]
You should add the option `with-3d`.

**Comment by alexgleith** [comment]
Ah, ok, so in a normal brew install, like `brew install qgis3-dev --with-3d`. I'll try it out. Thanks!
