### ISSUE TITLE
Compiled against GDAL 1.11.5, running against 2.1.2

### ISSUE THREAD

**Issue by Gustry** [qgis/homebrew-qgisdev#9]
Thanks a lot for this repository, very nice to compile QGIS on mac now !

I just noticed this on my build : 
![screen shot 2016-12-14 at 12 21 19](https://cloud.githubusercontent.com/assets/1609292/21180166/029b0f24-c1f8-11e6-873d-c89cfaf0fcad.png)
Sorry, I don't know if it's related to the formula or to my environment.
I checked in my `ccmake`, it's using gdal2 only.
Is-it normal or should I fix something on my build ?

Etienne

**Comment by nextstopsun** [comment]
Same message here

**Comment by dakcarto** [comment]
Please `brew unlink gdal` then `brew reinstall -dv qgis3-dev` to see it that fixes the issue. You can `brew link gdal` afterwards. I have to do some CMake search path tricks to keep GDAL 1.11.x headers from sneaking in (if it is installed), since it is usually installed in `/usr/local` and readily found by CMake. Looks like I missed one.

However, this does not necessarily mean that QGIS was compiled against GDAL 1.11.x (need to check CMake setup on this). Ran into this before. If GDAL 1.11.x headers are actually used, but QGIS is linked against GDAL 2.x, then compilation will fail during linking due to missing symbols.

Before reinstallling, could you verify which `libgdal` install name path is linked in the output of:
```
otool -L /usr/local/opt/qgis3-dev/QGIS.app/Contents/MacOS/QGIS
```

**Comment by nextstopsun** [comment]
Mine points to 
```
/usr/local/opt/gdal2/lib/libgdal.20.dylib (compatibility version 22.0.0, current version 22.2.0)
```

**Comment by Gustry** [comment]
The same for me.

Thanks Larry, it could fix the issue.
Should we close it or do you the ticket to improve the CMake search ?

**Comment by dakcarto** [comment]
Ok, should be 'fixed' with e7b3ef1. Please `brew update` and try again.

NOTE: review #11 first, as that may cause issues for you as well.

**Comment by Gustry** [comment]
Hi Larry,

It seems I broke something since a few days. I don't know if it's related. When I launch QGIS dev, I got this now : 
```
Couldn't load plugin 'processing' 

ModuleNotFoundError: No module named 'osgeo' 
Traceback (most recent call last):
  File "/Users/etienne/dev/c/QGIS/build/output/python/qgis/utils.py", line 313, in loadPlugin
    __import__(packageName)
  File "/Users/etienne/dev/c/QGIS/build/output/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/etienne/dev/c/QGIS/build/output/python/plugins/processing/__init__.py", line 28, in 
    from processing.tools.dataobjects import *          # NOQA
  File "/Users/etienne/dev/c/QGIS/build/output/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/etienne/dev/c/QGIS/build/output/python/plugins/processing/tools/dataobjects.py", line 47, in 
    from processing.algs.gdal.GdalUtils import GdalUtils
  File "/Users/etienne/dev/c/QGIS/build/output/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/etienne/dev/c/QGIS/build/output/python/plugins/processing/algs/gdal/GdalUtils.py", line 35, in 
    from osgeo import gdal
  File "/Users/etienne/dev/c/QGIS/build/output/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'osgeo'


Python version: 3.6.0 (default, Dec 28 2016, 09:41:05) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] 
QGIS version: 2.99.0-Master Master, 47130a6758 

Python Path:
/Users/etienne/dev/c/QGIS/build/output/python
/Users/etienne/.qgis3/python
/Users/etienne/.qgis3/python/plugins
/Users/etienne/dev/c/QGIS/build/output/python/plugins
/usr/local/opt/gdal2-python/lib/python3.6/site-packages
/usr/local/lib/python3.6/site-packages
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/etienne/.qgis3//python
```

**Comment by dakcarto** [comment]
Hi Etienne,

Does the following path exist?
`/usr/local/opt/gdal2-python/lib/python3.6/site-packages`

If not, please review #11.

**Comment by Gustry** [comment]
Ok, thanks sorry I missed this note.
